/**
 * Downloads the real asset marks and generates the static require map.
 *
 * Unlike the app icon, these are *not* original artwork: a wallet has to show
 * the mark people recognise, so each asset's own logo is fetched once and
 * bundled. Crypto marks come from CoinGecko, which is already this app's price
 * source, so the logo and the quote always agree about what the asset is.
 * Equity marks come from Financial Modeling Prep's public image endpoint.
 *
 * They are bundled rather than loaded at runtime for three reasons: the app
 * must work offline, Metro cannot resolve a dynamic require, and a wallet that
 * phones a third party on every render leaks which assets a user holds.
 *
 * Re-run after adding an asset. Existing files are kept unless --force is
 * passed, so a normal run costs nothing and never hammers either endpoint.
 *
 *   node tools/fetch-logos.mjs [--force]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'assets', 'logos');
const MAP = join(ROOT, 'src', 'data', 'logos.ts');

const FORCE = process.argv.includes('--force');
const UA = 'titanium-wallet/1.0 (personal demo build)';

/** Crypto: keyed by the token id used in src/data/tokens.ts. */
const CRYPTO = [
  'bitcoin',
  'ethereum',
  'solana',
  'tether',
  'usd-coin',
  'sui',
  'polygon-ecosystem-token',
  'bonk',
  'jupiter-exchange-solana',
  'raydium',
  'jito-governance-token',
  'pyth-network',
];

/** Equities: token id -> ticker used by the image endpoint. */
const STOCKS = {
  'stock-aapl': 'AAPL',
  'stock-nvda': 'NVDA',
  'stock-tsla': 'TSLA',
  'stock-msft': 'MSFT',
  'stock-amzn': 'AMZN',
};

const PACE_MS = 1500; // CoinGecko's free tier throttles hard above ~1 call/s.

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function get(url, asJson) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
  return asJson ? response.json() : Buffer.from(await response.arrayBuffer());
}

/** A PNG we can actually bundle, rather than an HTML error page saved as .png. */
function isPng(buffer) {
  return (
    buffer.length > 1000 &&
    buffer[0] === 0x89 &&
    buffer[1] === 0x50 &&
    buffer[2] === 0x4e &&
    buffer[3] === 0x47
  );
}

async function save(id, url) {
  const target = join(OUT, `${id}.png`);
  if (existsSync(target) && !FORCE) {
    console.log(`  ${id.padEnd(26)} cached`);
    return true;
  }
  try {
    const buffer = await get(url, false);
    if (!isPng(buffer)) {
      console.log(`  ${id.padEnd(26)} SKIPPED (not a png, ${buffer.length} bytes)`);
      return false;
    }
    writeFileSync(target, buffer);
    console.log(`  ${id.padEnd(26)} ${buffer.length} bytes`);
    return true;
  } catch (error) {
    console.log(`  ${id.padEnd(26)} FAILED ${error.message}`);
    return false;
  }
}

async function main() {
  mkdirSync(OUT, { recursive: true });
  const written = [];

  console.log('crypto marks (CoinGecko)');
  for (const id of CRYPTO) {
    const target = join(OUT, `${id}.png`);
    if (existsSync(target) && !FORCE) {
      console.log(`  ${id.padEnd(26)} cached`);
      written.push(id);
      continue;
    }
    try {
      const meta = await get(
        `https://api.coingecko.com/api/v3/coins/${id}?localization=false&tickers=false` +
          `&market_data=false&community_data=false&developer_data=false`,
        true,
      );
      const url = meta?.image?.large ?? meta?.image?.small;
      if (!url) {
        console.log(`  ${id.padEnd(26)} SKIPPED (no image in response)`);
        continue;
      }
      if (await save(id, url)) written.push(id);
    } catch (error) {
      console.log(`  ${id.padEnd(26)} FAILED ${error.message}`);
    }
    await sleep(PACE_MS);
  }

  console.log('\nequity marks (Financial Modeling Prep)');
  for (const [id, ticker] of Object.entries(STOCKS)) {
    const url = `https://financialmodelingprep.com/image-stock/${ticker}.png`;
    if (await save(id, url)) written.push(id);
    await sleep(300);
  }

  const entries = written
    .sort()
    .map((id) => `  '${id}': require('../../assets/logos/${id}.png'),`)
    .join('\n');

  writeFileSync(
    MAP,
    `/**
 * Static map of asset id -> bundled logo.
 *
 * GENERATED by tools/fetch-logos.mjs - do not edit by hand.
 *
 * Metro resolves require() at build time, so the paths have to be literals;
 * that is the only reason this file exists rather than building the path from
 * the id at the call site. An asset missing here falls back to the generated
 * monogram badge in TokenIcon, so a failed download degrades rather than
 * crashes.
 */
import { ImageSourcePropType } from 'react-native';

export const ASSET_LOGOS: Record<string, ImageSourcePropType> = {
${entries}
};

export function logoFor(id: string): ImageSourcePropType | undefined {
  return ASSET_LOGOS[id];
}
`,
    'utf8',
  );

  console.log(`\n${written.length} logos -> assets/logos/`);
  console.log(`map -> ${MAP.replace(ROOT, '.')}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
