/**
 * Generates src/data/bip39.ts from the canonical BIP-39 English wordlist.
 *
 * The list is only used to render a realistic-looking recovery phrase on the
 * onboarding screen. Nothing in the app derives keys from it.
 */
import { writeFileSync } from 'node:fs';

const SOURCE = 'https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt';

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`Failed to fetch wordlist: ${res.status}`);

const words = (await res.text())
  .split('\n')
  .map((w) => w.trim())
  .filter(Boolean);

if (words.length !== 2048) {
  throw new Error(`Expected 2048 words, received ${words.length}`);
}

// Wrap at a sensible width so the generated file stays readable in review.
const lines = [];
for (let i = 0; i < words.length; i += 8) {
  lines.push('  ' + words.slice(i, i + 8).map((w) => `'${w}'`).join(', ') + ',');
}

const file = `/**
 * The 2048-word BIP-39 English wordlist.
 *
 * Generated by tools/gen-bip39.mjs - do not edit by hand.
 *
 * Titanium is a demo wallet. This list exists so the onboarding screen can show
 * a phrase that *looks* authentic; no seed, key or address is ever derived from
 * it, and the generated words are cosmetic only.
 */

export const BIP39_WORDLIST: readonly string[] = [
${lines.join('\n')}
];
`;

writeFileSync(new URL('../src/data/bip39.ts', import.meta.url), file);
console.log(`Wrote src/data/bip39.ts with ${words.length} words.`);
